// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPt6yb0PzLYjJQ3jJsUuCNCcDo_BxId0c',
    appId: '1:248626827956:web:6d0f4489398984e7bf7de1',
    messagingSenderId: '248626827956',
    projectId: 'foodshare-6baee',
    authDomain: 'foodshare-6baee.firebaseapp.com',
    databaseURL: 'https://foodshare-6baee-default-rtdb.firebaseio.com',
    storageBucket: 'foodshare-6baee.appspot.com',
    measurementId: 'G-M9C13G6XB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMg_g80lkOuLwwZLC1qoDpwT4EnsRKpiI',
    appId: '1:248626827956:android:bc2904574ab8fee8bf7de1',
    messagingSenderId: '248626827956',
    projectId: 'foodshare-6baee',
    databaseURL: 'https://foodshare-6baee-default-rtdb.firebaseio.com',
    storageBucket: 'foodshare-6baee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7JT6hNh8e6tFj7xZu87aoVYgoOOTeOY',
    appId: '1:248626827956:ios:af365ca50a26173cbf7de1',
    messagingSenderId: '248626827956',
    projectId: 'foodshare-6baee',
    databaseURL: 'https://foodshare-6baee-default-rtdb.firebaseio.com',
    storageBucket: 'foodshare-6baee.appspot.com',
    iosBundleId: 'com.example.foodshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7JT6hNh8e6tFj7xZu87aoVYgoOOTeOY',
    appId: '1:248626827956:ios:eaff9a22543a622cbf7de1',
    messagingSenderId: '248626827956',
    projectId: 'foodshare-6baee',
    databaseURL: 'https://foodshare-6baee-default-rtdb.firebaseio.com',
    storageBucket: 'foodshare-6baee.appspot.com',
    iosBundleId: 'com.example.foodshare.RunnerTests',
  );
}
